export interface ReignRange {
  start: number
  end: number
  label: string
}

export interface MonarchEvent {
  id: string
  year: number
  label: string
  detail?: string
}

export interface Monarch {
  id: string
  name: string
  house: string
  reigns: ReignRange[]
  dateLabel: string
  aliases: string[]
  wikipediaTitle: string
  portraitFallback: string
  events: MonarchEvent[]
}

export interface HousePeriod {
  id: string
  label: string
  start: number
  end: number
  color: string
}

const currentYear = new Date().getFullYear()

export const WORLD_START_YEAR = 1050
export const WORLD_END_YEAR = currentYear + 1

export const housePeriods: HousePeriod[] = [
  { id: 'normandy', label: 'House of Normandy', start: 1066, end: 1154, color: '#6c4b3a' },
  { id: 'angevin', label: 'Angevins', start: 1154, end: 1216, color: '#8b5e34' },
  { id: 'plantagenet', label: 'Plantagenets', start: 1216, end: 1399, color: '#3f6b55' },
  { id: 'lancaster-a', label: 'Lancastrians', start: 1399, end: 1461, color: '#7f2f2f' },
  { id: 'york-a', label: 'Yorkists', start: 1461, end: 1470.8, color: '#355d8d' },
  { id: 'lancaster-b', label: 'Lancastrians', start: 1470.8, end: 1471.3, color: '#7f2f2f' },
  { id: 'york-b', label: 'Yorkists', start: 1471.3, end: 1485, color: '#355d8d' },
  { id: 'tudor', label: 'Tudors', start: 1485, end: 1603, color: '#7b4d26' },
  { id: 'stuart-a', label: 'Stuarts', start: 1603, end: 1649.1, color: '#4f4672' },
  { id: 'interregnum', label: 'Interregnum', start: 1649.1, end: 1660.4, color: '#5b5b5b' },
  { id: 'stuart-b', label: 'Stuarts', start: 1660.4, end: 1714.6, color: '#4f4672' },
  { id: 'hanover', label: 'Hanoverians', start: 1714.6, end: 1901.1, color: '#245663' },
  { id: 'saxe-coburg-gotha', label: 'Saxe-Coburg-Gotha', start: 1901.1, end: 1917.55, color: '#4e6761' },
  { id: 'windsor', label: 'Windsor', start: 1917.55, end: WORLD_END_YEAR, color: '#1d4d5a' },
]

export const monarchs: Monarch[] = [
  {
    id: 'william-i',
    name: 'William I',
    house: 'House of Normandy',
    reigns: [{ start: 1066.8, end: 1087.7, label: '1066-1087' }],
    dateLabel: '1066-1087',
    aliases: ['william the conqueror', 'william conqueror'],
    wikipediaTitle: 'William_the_Conqueror',
    portraitFallback: 'WI',
    events: [
      { id: 'hastings', year: 1066, label: 'Battle of Hastings' },
      { id: 'domesday', year: 1086, label: 'Domesday Book completed' },
    ],
  },
  {
    id: 'william-ii',
    name: 'William II',
    house: 'House of Normandy',
    reigns: [{ start: 1087.7, end: 1100.7, label: '1087-1100' }],
    dateLabel: '1087-1100',
    aliases: ['william rufus'],
    wikipediaTitle: 'William_II_of_England',
    portraitFallback: 'WII',
    events: [{ id: 'new-forest', year: 1100, label: 'Killed in the New Forest' }],
  },
  {
    id: 'henry-i',
    name: 'Henry I',
    house: 'House of Normandy',
    reigns: [{ start: 1100.7, end: 1135.95, label: '1100-1135' }],
    dateLabel: '1100-1135',
    aliases: ['henry beauclerc'],
    wikipediaTitle: 'Henry_I_of_England',
    portraitFallback: 'HI',
    events: [
      { id: 'white-ship', year: 1120, label: 'White Ship disaster' },
      { id: 'treasury', year: 1130, label: 'Pipe Roll records royal finance' },
    ],
  },
  {
    id: 'stephen',
    name: 'Stephen',
    house: 'House of Blois',
    reigns: [{ start: 1135.95, end: 1154.8, label: '1135-1154' }],
    dateLabel: '1135-1154',
    aliases: ['king stephen', 'stephen of blois'],
    wikipediaTitle: 'Stephen,_King_of_England',
    portraitFallback: 'S',
    events: [{ id: 'anarchy', year: 1139, label: 'The Anarchy' }],
  },
  {
    id: 'matilda',
    name: 'Empress Matilda',
    house: 'House of Normandy',
    reigns: [{ start: 1141.1, end: 1141.75, label: '1141' }],
    dateLabel: '1141',
    aliases: ['matilda', 'empress maud', 'maud'],
    wikipediaTitle: 'Empress_Matilda',
    portraitFallback: 'EM',
    events: [{ id: 'lady-of-english', year: 1141, label: 'Proclaimed Lady of the English' }],
  },
  {
    id: 'henry-ii',
    name: 'Henry II',
    house: 'Angevins',
    reigns: [{ start: 1154.8, end: 1189.5, label: '1154-1189' }],
    dateLabel: '1154-1189',
    aliases: ['henry fitzempress'],
    wikipediaTitle: 'Henry_II_of_England',
    portraitFallback: 'HII',
    events: [
      { id: 'becket', year: 1170, label: 'Thomas Becket murdered' },
      { id: 'ireland', year: 1171, label: 'Henry lands in Ireland' },
    ],
  },
  {
    id: 'richard-i',
    name: 'Richard I',
    house: 'Angevins',
    reigns: [{ start: 1189.5, end: 1199.25, label: '1189-1199' }],
    dateLabel: '1189-1199',
    aliases: ['richard the lionheart', 'lionheart'],
    wikipediaTitle: 'Richard_I_of_England',
    portraitFallback: 'RI',
    events: [
      { id: 'third-crusade', year: 1191, label: 'Third Crusade' },
      { id: 'lionheart', year: 1192, label: 'Richard the Lionheart legend grows' },
    ],
  },
  {
    id: 'john',
    name: 'John',
    house: 'Angevins',
    reigns: [{ start: 1199.25, end: 1216.75, label: '1199-1216' }],
    dateLabel: '1199-1216',
    aliases: ['king john', 'john lackland'],
    wikipediaTitle: 'John,_King_of_England',
    portraitFallback: 'J',
    events: [
      { id: 'magna-carta', year: 1215, label: 'Magna Carta sealed' },
      { id: 'barons-war', year: 1215, label: "First Barons' War begins" },
    ],
  },
  {
    id: 'henry-iii',
    name: 'Henry III',
    house: 'Plantagenets',
    reigns: [{ start: 1216.75, end: 1272.9, label: '1216-1272' }],
    dateLabel: '1216-1272',
    aliases: [],
    wikipediaTitle: 'Henry_III_of_England',
    portraitFallback: 'HIII',
    events: [
      { id: 'montfort', year: 1265, label: "Simon de Montfort's Parliament" },
      { id: 'westminster-abbey', year: 1245, label: 'Westminster Abbey rebuilt' },
    ],
  },
  {
    id: 'edward-i',
    name: 'Edward I',
    house: 'Plantagenets',
    reigns: [{ start: 1272.9, end: 1307.55, label: '1272-1307' }],
    dateLabel: '1272-1307',
    aliases: ['edward longshanks', 'longshanks'],
    wikipediaTitle: 'Edward_I_of_England',
    portraitFallback: 'EI',
    events: [
      { id: 'wales', year: 1284, label: 'Statute of Rhuddlan after conquest of Wales' },
      { id: 'model-parliament', year: 1295, label: 'Model Parliament' },
    ],
  },
  {
    id: 'edward-ii',
    name: 'Edward II',
    house: 'Plantagenets',
    reigns: [{ start: 1307.55, end: 1327.1, label: '1307-1327' }],
    dateLabel: '1307-1327',
    aliases: [],
    wikipediaTitle: 'Edward_II_of_England',
    portraitFallback: 'EII',
    events: [{ id: 'bannockburn', year: 1314, label: 'Battle of Bannockburn' }],
  },
  {
    id: 'edward-iii',
    name: 'Edward III',
    house: 'Plantagenets',
    reigns: [{ start: 1327.1, end: 1377.5, label: '1327-1377' }],
    dateLabel: '1327-1377',
    aliases: [],
    wikipediaTitle: 'Edward_III_of_England',
    portraitFallback: 'EIII',
    events: [
      { id: 'hundred-years-war', year: 1346, label: "Crecy in the Hundred Years' War" },
      { id: 'black-death', year: 1348, label: 'Black Death reaches England' },
    ],
  },
  {
    id: 'richard-ii',
    name: 'Richard II',
    house: 'Plantagenets',
    reigns: [{ start: 1377.5, end: 1399.8, label: '1377-1399' }],
    dateLabel: '1377-1399',
    aliases: [],
    wikipediaTitle: 'Richard_II_of_England',
    portraitFallback: 'RII',
    events: [
      { id: 'peasants-revolt', year: 1381, label: "Peasants' Revolt" },
      { id: 'deposed', year: 1399, label: 'Deposed by Henry Bolingbroke' },
    ],
  },
  {
    id: 'henry-iv',
    name: 'Henry IV',
    house: 'Lancastrians',
    reigns: [{ start: 1399.8, end: 1413.2, label: '1399-1413' }],
    dateLabel: '1399-1413',
    aliases: [],
    wikipediaTitle: 'Henry_IV_of_England',
    portraitFallback: 'HIV',
    events: [{ id: 'deposition', year: 1399, label: 'Seizes the throne from Richard II' }],
  },
  {
    id: 'henry-v',
    name: 'Henry V',
    house: 'Lancastrians',
    reigns: [{ start: 1413.2, end: 1422.65, label: '1413-1422' }],
    dateLabel: '1413-1422',
    aliases: [],
    wikipediaTitle: 'Henry_V_of_England',
    portraitFallback: 'HV',
    events: [
      { id: 'agincourt', year: 1415, label: 'Battle of Agincourt' },
      { id: 'troyes', year: 1420, label: 'Treaty of Troyes' },
    ],
  },
  {
    id: 'henry-vi',
    name: 'Henry VI',
    house: 'Lancastrians',
    reigns: [
      { start: 1422.65, end: 1461.2, label: '1422-1461' },
      { start: 1470.8, end: 1471.3, label: '1470-1471' },
    ],
    dateLabel: '1422-1461, 1470-1471',
    aliases: [],
    wikipediaTitle: 'Henry_VI_of_England',
    portraitFallback: 'HVI',
    events: [
      { id: 'wars-of-roses', year: 1455, label: 'Wars of the Roses begin' },
      { id: 'madness', year: 1453, label: 'Henry VI suffers mental collapse' },
    ],
  },
  {
    id: 'edward-iv',
    name: 'Edward IV',
    house: 'Yorkists',
    reigns: [
      { start: 1461.2, end: 1470.8, label: '1461-1470' },
      { start: 1471.3, end: 1483.35, label: '1471-1483' },
    ],
    dateLabel: '1461-1470, 1471-1483',
    aliases: [],
    wikipediaTitle: 'Edward_IV_of_England',
    portraitFallback: 'EIV',
    events: [
      { id: 'towton', year: 1461, label: 'Battle of Towton' },
      { id: 'tewkesbury', year: 1471, label: 'Battle of Tewkesbury' },
    ],
  },
  {
    id: 'edward-v',
    name: 'Edward V',
    house: 'Yorkists',
    reigns: [{ start: 1483.35, end: 1483.52, label: '1483' }],
    dateLabel: '1483',
    aliases: [],
    wikipediaTitle: 'Edward_V_of_England',
    portraitFallback: 'EV',
    events: [{ id: 'princes-tower', year: 1483, label: 'One of the Princes in the Tower' }],
  },
  {
    id: 'richard-iii',
    name: 'Richard III',
    house: 'Yorkists',
    reigns: [{ start: 1483.52, end: 1485.65, label: '1483-1485' }],
    dateLabel: '1483-1485',
    aliases: [],
    wikipediaTitle: 'Richard_III_of_England',
    portraitFallback: 'RIII',
    events: [
      { id: 'princes-r3', year: 1483, label: 'Princes in the Tower' },
      { id: 'bosworth', year: 1485, label: 'Battle of Bosworth Field' },
    ],
  },
  {
    id: 'henry-vii',
    name: 'Henry VII',
    house: 'Tudors',
    reigns: [{ start: 1485.65, end: 1509.25, label: '1485-1509' }],
    dateLabel: '1485-1509',
    aliases: [],
    wikipediaTitle: 'Henry_VII_of_England',
    portraitFallback: 'HVII',
    events: [
      { id: 'bosworth-h7', year: 1485, label: 'Wins the crown at Bosworth' },
      { id: 'tudor-rose', year: 1486, label: 'Marriage unites Lancaster and York' },
    ],
  },
  {
    id: 'henry-viii',
    name: 'Henry VIII',
    house: 'Tudors',
    reigns: [{ start: 1509.25, end: 1547.05, label: '1509-1547' }],
    dateLabel: '1509-1547',
    aliases: [],
    wikipediaTitle: 'Henry_VIII',
    portraitFallback: 'HVIII',
    events: [
      { id: 'break-rome', year: 1534, label: 'Break with Rome' },
      { id: 'dissolution', year: 1536, label: 'Dissolution of the monasteries' },
    ],
  },
  {
    id: 'edward-vi',
    name: 'Edward VI',
    house: 'Tudors',
    reigns: [{ start: 1547.05, end: 1553.52, label: '1547-1553' }],
    dateLabel: '1547-1553',
    aliases: [],
    wikipediaTitle: 'Edward_VI',
    portraitFallback: 'EVI',
    events: [
      { id: 'prayer-book', year: 1549, label: 'Book of Common Prayer' },
      { id: 'somerset', year: 1549, label: "Kett's Rebellion" },
    ],
  },
  {
    id: 'jane-grey',
    name: 'Lady Jane Grey',
    house: 'Tudors',
    reigns: [{ start: 1553.52, end: 1553.55, label: '1553' }],
    dateLabel: '1553',
    aliases: ['jane grey', 'queen jane'],
    wikipediaTitle: 'Lady_Jane_Grey',
    portraitFallback: 'JG',
    events: [{ id: 'nine-days', year: 1553, label: "Nine Days' Queen" }],
  },
  {
    id: 'mary-i',
    name: 'Mary I',
    house: 'Tudors',
    reigns: [{ start: 1553.55, end: 1558.85, label: '1553-1558' }],
    dateLabel: '1553-1558',
    aliases: ['bloody mary'],
    wikipediaTitle: 'Mary_I_of_England',
    portraitFallback: 'MI',
    events: [
      { id: 'bloody-mary', year: 1555, label: 'Burning of Protestants' },
      { id: 'calais', year: 1558, label: 'England loses Calais' },
    ],
  },
  {
    id: 'elizabeth-i',
    name: 'Elizabeth I',
    house: 'Tudors',
    reigns: [{ start: 1558.85, end: 1603.22, label: '1558-1603' }],
    dateLabel: '1558-1603',
    aliases: ['gloriana', 'good queen bess'],
    wikipediaTitle: 'Elizabeth_I',
    portraitFallback: 'EI',
    events: [
      { id: 'armada', year: 1588, label: 'Spanish Armada defeated' },
      { id: 'mary-queen-scots', year: 1587, label: 'Mary, Queen of Scots executed' },
    ],
  },
  {
    id: 'james-i',
    name: 'James I',
    house: 'Stuarts',
    reigns: [{ start: 1603.22, end: 1625.25, label: '1603-1625' }],
    dateLabel: '1603-1625',
    aliases: ['james vi and i', 'james 6 and 1'],
    wikipediaTitle: 'James_VI_and_I',
    portraitFallback: 'JI',
    events: [
      { id: 'gunpowder', year: 1605, label: 'Gunpowder Plot' },
      { id: 'king-james-bible', year: 1611, label: 'King James Bible published' },
    ],
  },
  {
    id: 'charles-i',
    name: 'Charles I',
    house: 'Stuarts',
    reigns: [{ start: 1625.25, end: 1649.08, label: '1625-1649' }],
    dateLabel: '1625-1649',
    aliases: [],
    wikipediaTitle: 'Charles_I_of_England',
    portraitFallback: 'CI',
    events: [
      { id: 'civil-war', year: 1642, label: 'English Civil War begins' },
      { id: 'execution-c1', year: 1649, label: 'Charles I executed' },
    ],
  },
  {
    id: 'charles-ii',
    name: 'Charles II',
    house: 'Stuarts',
    reigns: [{ start: 1660.41, end: 1685.1, label: '1660-1685' }],
    dateLabel: '1660-1685',
    aliases: ['the merry monarch'],
    wikipediaTitle: 'Charles_II_of_England',
    portraitFallback: 'CII',
    events: [
      { id: 'restoration', year: 1660, label: 'The Restoration' },
      { id: 'great-fire', year: 1666, label: 'Great Fire of London' },
    ],
  },
  {
    id: 'james-ii',
    name: 'James II',
    house: 'Stuarts',
    reigns: [{ start: 1685.1, end: 1688.92, label: '1685-1688' }],
    dateLabel: '1685-1688',
    aliases: [],
    wikipediaTitle: 'James_II_of_England',
    portraitFallback: 'JII',
    events: [{ id: 'glorious-revolution', year: 1688, label: 'Glorious Revolution' }],
  },
  {
    id: 'william-iii',
    name: 'William III',
    house: 'Stuarts',
    reigns: [{ start: 1689.12, end: 1702.2, label: '1689-1702' }],
    dateLabel: '1689-1702',
    aliases: ['william of orange'],
    wikipediaTitle: 'William_III_of_England',
    portraitFallback: 'WIII',
    events: [
      { id: 'glorious-revolution-w3', year: 1688, label: 'Glorious Revolution' },
      { id: 'boyne', year: 1690, label: 'Battle of the Boyne' },
    ],
  },
  {
    id: 'mary-ii',
    name: 'Mary II',
    house: 'Stuarts',
    reigns: [{ start: 1689.12, end: 1694.95, label: '1689-1694' }],
    dateLabel: '1689-1694',
    aliases: [],
    wikipediaTitle: 'Mary_II_of_England',
    portraitFallback: 'MII',
    events: [{ id: 'joint-rule', year: 1689, label: 'Joint rule with William III begins' }],
  },
  {
    id: 'anne',
    name: 'Anne',
    house: 'Stuarts',
    reigns: [{ start: 1702.2, end: 1714.6, label: '1702-1714' }],
    dateLabel: '1702-1714',
    aliases: ['queen anne'],
    wikipediaTitle: 'Anne,_Queen_of_Great_Britain',
    portraitFallback: 'A',
    events: [
      { id: 'union', year: 1707, label: 'Acts of Union' },
      { id: 'marlborough', year: 1704, label: 'Blenheim in the War of the Spanish Succession' },
    ],
  },
  {
    id: 'george-i',
    name: 'George I',
    house: 'Hanoverians',
    reigns: [{ start: 1714.6, end: 1727.45, label: '1714-1727' }],
    dateLabel: '1714-1727',
    aliases: [],
    wikipediaTitle: 'George_I_of_Great_Britain',
    portraitFallback: 'GI',
    events: [{ id: 'jacobite-1715', year: 1715, label: 'Jacobite rising of 1715' }],
  },
  {
    id: 'george-ii',
    name: 'George II',
    house: 'Hanoverians',
    reigns: [{ start: 1727.45, end: 1760.75, label: '1727-1760' }],
    dateLabel: '1727-1760',
    aliases: [],
    wikipediaTitle: 'George_II_of_Great_Britain',
    portraitFallback: 'GII',
    events: [{ id: 'jacobite-1745', year: 1745, label: 'Jacobite rising of 1745' }],
  },
  {
    id: 'george-iii',
    name: 'George III',
    house: 'Hanoverians',
    reigns: [{ start: 1760.75, end: 1820.1, label: '1760-1820' }],
    dateLabel: '1760-1820',
    aliases: [],
    wikipediaTitle: 'George_III',
    portraitFallback: 'GIII',
    events: [
      { id: 'american-independence', year: 1776, label: 'American colonies declare independence' },
      { id: 'napoleon', year: 1815, label: 'Waterloo ends the Napoleonic Wars' },
    ],
  },
  {
    id: 'george-iv',
    name: 'George IV',
    house: 'Hanoverians',
    reigns: [{ start: 1820.1, end: 1830.5, label: '1820-1830' }],
    dateLabel: '1820-1830',
    aliases: [],
    wikipediaTitle: 'George_IV',
    portraitFallback: 'GIV',
    events: [{ id: 'regency', year: 1811, label: 'Regency era begins' }],
  },
  {
    id: 'william-iv',
    name: 'William IV',
    house: 'Hanoverians',
    reigns: [{ start: 1830.5, end: 1837.48, label: '1830-1837' }],
    dateLabel: '1830-1837',
    aliases: [],
    wikipediaTitle: 'William_IV',
    portraitFallback: 'WIV',
    events: [{ id: 'reform-act', year: 1832, label: 'Great Reform Act' }],
  },
  {
    id: 'victoria',
    name: 'Victoria',
    house: 'Hanoverians',
    reigns: [{ start: 1837.48, end: 1901.02, label: '1837-1901' }],
    dateLabel: '1837-1901',
    aliases: ['queen victoria'],
    wikipediaTitle: 'Queen_Victoria',
    portraitFallback: 'V',
    events: [
      { id: 'great-exhibition', year: 1851, label: 'Great Exhibition' },
      { id: 'jubilee', year: 1897, label: 'Diamond Jubilee' },
    ],
  },
  {
    id: 'edward-vii',
    name: 'Edward VII',
    house: 'Saxe-Coburg-Gotha',
    reigns: [{ start: 1901.02, end: 1910.37, label: '1901-1910' }],
    dateLabel: '1901-1910',
    aliases: [],
    wikipediaTitle: 'Edward_VII',
    portraitFallback: 'EVII',
    events: [{ id: 'edwardian-age', year: 1901, label: 'The Edwardian age begins' }],
  },
  {
    id: 'george-v',
    name: 'George V',
    house: 'Windsor',
    reigns: [{ start: 1910.37, end: 1936.02, label: '1910-1936' }],
    dateLabel: '1910-1936',
    aliases: [],
    wikipediaTitle: 'George_V',
    portraitFallback: 'GV',
    events: [
      { id: 'first-world-war', year: 1914, label: 'Britain enters the First World War' },
      { id: 'windsor-name', year: 1917, label: 'House of Windsor adopted' },
    ],
  },
  {
    id: 'edward-viii',
    name: 'Edward VIII',
    house: 'Windsor',
    reigns: [{ start: 1936.02, end: 1936.95, label: '1936' }],
    dateLabel: '1936',
    aliases: [],
    wikipediaTitle: 'Edward_VIII',
    portraitFallback: 'EVIII',
    events: [{ id: 'abdication', year: 1936, label: 'Abdication crisis' }],
  },
  {
    id: 'george-vi',
    name: 'George VI',
    house: 'Windsor',
    reigns: [{ start: 1936.95, end: 1952.1, label: '1936-1952' }],
    dateLabel: '1936-1952',
    aliases: [],
    wikipediaTitle: 'George_VI',
    portraitFallback: 'GVI',
    events: [
      { id: 'second-world-war', year: 1939, label: 'Second World War begins' },
      { id: 'blitz', year: 1940, label: 'The Blitz' },
    ],
  },
  {
    id: 'elizabeth-ii',
    name: 'Elizabeth II',
    house: 'Windsor',
    reigns: [{ start: 1952.1, end: 2022.69, label: '1952-2022' }],
    dateLabel: '1952-2022',
    aliases: [],
    wikipediaTitle: 'Elizabeth_II',
    portraitFallback: 'EII',
    events: [
      { id: 'televised-coronation', year: 1953, label: 'Televised coronation' },
      { id: 'platinum-jubilee', year: 2022, label: 'Platinum Jubilee' },
    ],
  },
  {
    id: 'charles-iii',
    name: 'Charles III',
    house: 'Windsor',
    reigns: [{ start: 2022.69, end: WORLD_END_YEAR, label: '2022-present' }],
    dateLabel: '2022-present',
    aliases: [],
    wikipediaTitle: 'Charles_III',
    portraitFallback: 'CIII',
    events: [
      { id: 'accession-c3', year: 2022, label: 'Succeeds Elizabeth II' },
      { id: 'coronation-2023', year: 2023, label: 'Coronation of Charles III' },
    ],
  },
]
